### ISSUE TITLE
使用 React 定义 TreeView  Item dom 的内容？

### ISSUE THREAD

**Issue by yiliang114** [LeuisKen/react-vsc-treeview#9]
前辈好，我想请教一个问题： `react-vsc-treeview` 您这个包，其实解决的是用我们习惯的 Dom 层级写法，书写 `vscode` `TreeView` ，本质上是用 `react` 的 `jsx` 将树的层级关系通过 `react-reconciler` 转成具有嵌套节点的根节点，再让 `vscode` 的 `TreeViewProvider` 的 `getChildren` API 读出每一层的数据并渲染？

所以看起来我们没办法用 `react` 去自定义每一项 `TreeView` 的 dom 结构，例如再加一个 icon 之类的？

**Comment by LeuisKen** [comment]
icon 我没记错的话可以用属性加上，但是调整结构是不行的。

**Comment by yiliang114** [comment]
嗯嗯 是的是的，明白了
